version: "3.4"

services:
  jafa-backend:
    container_name: jafa-backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - mongo

  jafa-frontend:
    container_name: jafa-frontend
    build:
      target: prod
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - jafa-backend
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
