version: "3.4"

services:
  jafa:
    volumes:
      - "./backend:/opt/jafa/backend:ro"
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8080",
        "backend.app:create_app()",
        "--reload",
      ]
