version: "3.4"

services:
  jafa:
    env_file:
      - .env
    volumes:
      - "./backend:/opt/jafa/backend:ro"
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8080",
        "--worker-class", "gevent",
        "backend.app:create_app()",
        "--reload",
      ]
  mongo:
    ports:
      - 27017:27017
