version: "3.4"

services:
  jafa-backend:
    volumes:
      - "./backend:/opt/jafa/backend:ro"
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8080",
        "--worker-class", "gevent",
        "backend.app:create_app()",
        "--reload",
      ]
  jafa-frontend:
    volumes:
      - "./frontend:/app"
    build:
      target: dev
  mongo:
    ports:
      - 27017:27017
